import React from "react"; // Import React to use JSX
import Photo from "../assets/photo.jpg";
import AboutInfo from "../data/AboutInfo.json" // Importing project data from the JSON file

function AboutContent () {

    // skills-container for skills list, dynamically generated by mapping over the AboutInfo JSON
    // Rendering each skill item and assigning a unique key (index here)
    return (
        <div>
            <div className="about-content">
                <div className="about-intro">
                    <img src={Photo} />
                    <div className="about-text">
                        <h1>About Me</h1>
                        <p> Hi, I’m Nancy, a graphic designer based in Vancouver, 
                            and an aspiring passionate about creating beautiful and functional designs. 
                            Currently, I’m enhancing my skills at BCIT in New Media Design while bringing my core values of integrity, responsibility, and perseverance to every project. Beyond design, 
                            I love hiking, capturing stunning photos, and exploring new flavors as a dedicated foodie.
                        </p>
                    </div>
                </div>
            </div>
            <h2 className="skill-title"> My Skills </h2>
            <div className="skills-container">
                {AboutInfo.map((item, index) => (
                    <div key={index} className="skill-item">
                    <img src={item.skill} alt={`Skill ${index}`} className="skill-image" />
                    </div>
                    ))}
            </div>
        </div>
    )
}

export default AboutContent;